# Site settings
title: SuiBuKan Thessaloniki
email: dervas@suibukan.com
description: "Suibukan - Shorin Ryu Karate in Thessaloniki by Suibukan"
baseurl: ""
url: "http://thes.suibukan.com"
sass:
    sass_dir: _sass
gems:
  - jekyll-sitemap
# Build settings
markdown: kramdown
permalink: /:categories/:title

defaults:
  -
    scope:
       path: ""
       type: "posts"
    values:
       layout: "posts-layout"
