# Site settings
title: SuiBuKan DOJO Thessaloniki
email: dervas@suibukan.com
description: "Shorin Ryu Karate clubs in Thessaloniki by Suibukan"
baseurl: ""
url: "http://thes.suibukan.com"
sass:
    sass_dir: _sass
collections:
  karatemasters:
    output: true
  kobudomasters:
    output: true
  karatekata:
    output: true
  kobudokata:
    output: true
     
# Build settings
markdown: kramdown
permalink: /:categories/:title

defaults:
  -
    scope:
       path: ""
       type: "posts"
    values:
       layout: "posts-layout"

prose:
  rooturl: '_posts'
  siteurl: 'http:thes.suibukan.com'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'assets/images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - css
    - js
    - _data
    - _sass
    - news
    - place
    - program
    - videos
    - faq
    - organization
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/articles:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _posts/dojo:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _posts/news:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "sticky at top of lists"
              value: "sticky"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
