# Site settings
title: SuiBuKan DOJO Techican
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll
sass:
    sass_dir: _sass
collections:
  karatemasters:
    output: true
  kobudomasters:
    output: true
  karatekata:
    output: true
  kobudokata:
    output: true
     
# Build settings
markdown: kramdown
permalink: /:categories/:title

defaults:
  -
    scope:
       path: ""
       type: "posts"
    values:
       layout: "posts-layout"
       category: "articles"
  -
    scope:
       path: ""
       type: "karatemasters"
    values:
       layout: "posts-layout"
  -
    scope:
       path: ""
       type: "kobudomasters"
    values:
       layout: "posts-layout"
  -
    scope:
       path: ""
       type: "karatekata"
    values:
       layout: "posts-layout"  
  -
    scope:
       path: ""
       type: "kobudokata"
    values:
       layout: "posts-layout"
  -
    scope:
       path: "martialarts"
       type: "posts"
    values:
       layout: "posts-layout"