# Site settings
title: SuiBuKan DOJO Thessaloniki
email: dervas@suibukan.com
description: "Shorin Ryu Karate clubs in Thessaloniki by Suibukan"
baseurl: ""
url: "http://thes.suibukan.com"
sass:
    sass_dir: _sass
collections:
  karatemasters:
    output: true
  kobudomasters:
    output: true
  karatekata:
    output: true
  kobudokata:
    output: true
     
# Build settings
markdown: kramdown
permalink: /:categories/:title

defaults:
  -
    scope:
       path: ""
       type: "post"
    values:
       layout: "posts-layout"
