# Site settings
title: SuiBuKan DOJO Thessaloniki
email: dervas@suibukan.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://thes.suibukan.com"
sass:
    sass_dir: _sass
collections:
  karatemasters:
    output: true
  kobudomasters:
    output: true
  karatekata:
    output: true
  kobudokata:
    output: true
     
# Build settings
markdown: kramdown
permalink: /:categories/:title

defaults:
  -
    scope:
       path: ""
       type: "post"
    values:
       layout: "posts-layout"
